<html>
<head>
<link rel="stylesheet" type="text/css" href="css/layout.css">
  <title>Results</title>
</head>
	<body id="top">
<div class="wrapper col1">
  <div id="topbar">
    <p>Tel: (678)334-6798 | Mail: Support@Vehicls4Harambe.com</p>
    <ul>
      <li><a href="#">Home</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Classifieds</a></li>
      <li class="last"><a href="login.html">Sign in</a></li>
    </ul>
    <br class="clear" />
  </div>
</div>
<!-- ####################################################################################################### -->
<div class="wrapper col2">
  <div id="header">
    <div class="fl_left">
      <h1><a href="index.html">Vehicles For Harambe</a></h1>
      <p>Be Strong For Harambe</p>
    </div>
    <div class="fl_right"> <a href="#"><img src="images/demo/468x60.gif" alt="" /></a> </div>
    <br class="clear" />
  </div>
</div>
<!-- ####################################################################################################### -->
<div class="wrapper col3">
  <div id="topnav">
    <ul>
      <li class="active"><a href="index.html">Homepage</a></li>
      <li><a href="pages/full-width.html">About Us</a></li>
      <li><a href="pages/full-width.html">Classifieds</a></li>
    </ul>
    <br class="clear" />
  </div>
</div>
  <h1>Information about: ${query}</h1>
    <#if query == "actors">
    <table border=1>
      <tr>
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Gender</th>
        <th>Film Count</th>
    </tr>
    <#list actors as actor>
      <tr><td>${actor.id}<td>${actor.firstName}<td>${actor.lastName}<td>${actor.gender}<td>${actor.filmCount}</tr>
    </#list>
  </table>
  </#if>

  <#if query == "movies">
  <table border=1>
    <tr>
    <th>Movie Name</th>
    <th>Movie ID</th>
    <th>Movie Year</th>
    <th>Movie Rank</th>
  </tr>
  <#list movies as movie>
    <tr><td>${movie.name}<td>${movie.id}<td>${movie.year}<td>${movie.rank}</tr>
  </#list>
  </table>
  </#if>

  <#if query == "directors">
  <table border=1>
    <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>ID</th>
  </tr>
  <#list directors as director>
    <tr><td>${director.firstName}<td>${director.lastName}<td>${director.id}</tr>
  </#list>
  </table>
  </#if>

  <#if query == "roles">
  <table border=1>
    <tr>
    <th>Actor ID</th>
    <th>Movie ID</th>
    <th>Role</th>
  </tr>
  <#list roles as role>
    <tr><td>${role.actorId}<td>${role.movieId}<td>${role.role}</tr>
  </#list>
  </table>
  </#if>

  <#if query == "directors_genres">
  <table border=1>
    <tr>
    <th>Director ID</th>
    <th>Genre</th>
    <th>Prob</th>
  </tr>
  <#list dirgenre as dirgen>
    <tr><td>${dirgen.directorId}<td>${dirgen.genre}<td>${dirgen.prob}</tr>
  </#list>
  </table>
  </#if>

  <#if query == "movies_directors">
  <table border=1>
    <tr>
    <th>Director ID</th>
    <th>Movie ID</th>
  </tr>
  <#list moviedir as mvd>
    <tr><td>${mvd.directorId}<td>${mvd.movieId}</tr>
  </#list>
  </table>
  </#if>

  <#if query == "movies_genres">
  <table border=1>
    <tr>
    <th>Movie ID</th>
    <th>Genre</th>
  </tr>
  <#list moviegen as mvg>
    <tr><td>${mvg.movieId}<td>${mvg.genre}</tr>
  </#list>
  </table>
  </#if>
</body>
</html>
